create database ECommerce;

USE [ECommerce] 
GO

CREATE TABLE CLIENT (
ID INT NOT NULL IDENTITY,
NOM varchar (200) null,
PRENOM varchar (200) null,
DATE_NAISSANCE date,
EMAIL varchar (200) null,
CONSTRAINT PK_CLIENT PRIMARY KEY(ID)
);

CREATE TABLE CATEGORIE (
ID INT NOT NULL IDENTITY,
IDMERE INT,
NOM varchar (200) null, 
CONSTRAINT PK_CATEGORIE PRIMARY KEY(ID),
CONSTRAINT FK_CATEGORIE_CATEGORIE FOREIGN KEY(IDMERE) REFERENCES CATEGORIE(ID)
);

CREATE TABLE PRODUITS (
ID INT NOT NULL IDENTITY,
IDCATEGORIE INT,
NOM varchar (200) null, 
DESCRIPTION varchar (200) null, 
CODE_BARRE varchar (200) null, 
LIEN_PHOTO varchar (200) null, 
PRIX FLOAT , 
REF varchar (20) not null,
CONSTRAINT PK_PRODUITS PRIMARY KEY(ID),
CONSTRAINT FK_PRODUITS_CATEGORIE FOREIGN KEY(IDCATEGORIE) REFERENCES CATEGORIE(ID)
);

CREATE TABLE PANIER (
ID INT NOT NULL IDENTITY,
PRIX FLOAT, 
CONSTRAINT PK_PANIER PRIMARY KEY(ID)
);

CREATE TABLE ELEMENTPANIER (
ID INT NOT NULL IDENTITY,
IDPANIER INT,
IDPRODUIT INT,
QUANTITE INT,
PRIX FLOAT, 
CONSTRAINT PK_ELEMENTPANIER PRIMARY KEY(ID),
CONSTRAINT FK_ELEMENTPANIER_PANIER FOREIGN KEY(IDPANIER) REFERENCES PANIER(ID),
CONSTRAINT FK_ELEMENTPANIER_PRODUIT FOREIGN KEY(IDPRODUIT) REFERENCES PRODUITS(ID)
);

CREATE TABLE COMMANDE (
ID INT NOT NULL IDENTITY,
IDCLIENT INT,
DATE_CDE DATE,
TOTALHT FLOAT, 
TOTALTVA FLOAT,
TOTALTTC FLOAT, 
CONSTRAINT PK_COMMANDE PRIMARY KEY(ID),
CONSTRAINT FK_COMMANDE_CLIENT FOREIGN KEY(IDCLIENT) REFERENCES CLIENT(ID)
);

CREATE TABLE LIGNE_CDE (
ID INT NOT NULL IDENTITY,
IDCOMMANDE INT,
QUANTITE INT,
PRIX_U FLOAT,
TOTALHT FLOAT, 
TOTALTVA FLOAT,
TOTALTTC FLOAT, 
CONSTRAINT PK_LIGNE_CDE PRIMARY KEY(ID),
CONSTRAINT FK_LIGNE_CDE_COMMANDE FOREIGN KEY(IDCOMMANDE) REFERENCES COMMANDE(ID)
);
CREATE TABLE TVA(
ID INT NOT NULL IDENTITY,
TAUX FLOAT, 
DATE_VAL DATE
);

CREATE TABLE FACTURE (
ID INT NOT NULL IDENTITY,
IDCLIENT INT,
IDCOMMANDE INT,
DATE_FACT DATE,
TOTALHT FLOAT, 
TOTALTVA FLOAT,
TOTALTTC FLOAT, 
CONSTRAINT PK_FACTURE PRIMARY KEY(ID),
CONSTRAINT FK_FACTURE_CLIENT FOREIGN KEY(IDCLIENT) REFERENCES CLIENT(ID),
CONSTRAINT FK_FACTURE_COMMANDE FOREIGN KEY(IDCOMMANDE) REFERENCES COMMANDE(ID)
);

CREATE TABLE LIGNE_FACT (
ID INT NOT NULL IDENTITY,
IDFACTURE INT,
QUANTITE INT,
PRIX_U FLOAT,
TOTALHT FLOAT, 
TOTALTVA FLOAT,
TOTALTTC FLOAT, 
CONSTRAINT PK_LIGNE_FACT PRIMARY KEY(ID),
CONSTRAINT FK_LIGNE_FACT_FACTURE FOREIGN KEY(IDFACTURE) REFERENCES FACTURE(ID)
);

CREATE TABLE ADRESSE (
ID INT NOT NULL IDENTITY,
IDCLIENT INT,
NOM varchar (200) null,
NUM INT,
RUE varchar (200) null,
CP varchar (5) null,
VILLE varchar (200) null,
CONSTRAINT PK_ADRESSE PRIMARY KEY(ID),
CONSTRAINT FK_ADRESSE_CLIENT FOREIGN KEY(IDCLIENT) REFERENCES CLIENT(ID)
);

CREATE TABLE COMPTE_BANCAIRE (
ID INT NOT NULL IDENTITY,
IDCLIENT INT,
NOM_COMPTE varchar (200) null,
NUM_COMPTE INT,
DATE_EXP DATE,
CLE INT,
CONSTRAINT PK_COMPTE_BANCAIRE PRIMARY KEY(ID),
CONSTRAINT FK_COMPTE_BANCAIRE_CLIENT FOREIGN KEY(IDCLIENT) REFERENCES CLIENT(ID)
);

CREATE TABLE CATALOGUE (
ID INT NOT NULL IDENTITY,
NOM varchar (200) null, 
DESCRIPTION varchar (200) null, 
CONSTRAINT PK_CATALOGUE PRIMARY KEY(ID)
);

CREATE TABLE ELEMENTCATALOGUE (
ID INT NOT NULL IDENTITY,
IDCATALOGUE INT,
IDPRODUIT INT,
CONSTRAINT PK_ELEMENTCATALOGUE PRIMARY KEY(ID),
CONSTRAINT FK_ELEMENTCATALOGUE_CATALOGUE FOREIGN KEY(IDCATALOGUE) REFERENCES CATALOGUE(ID),
CONSTRAINT FK_ELEMENTCATALOGUE_PRODUIT FOREIGN KEY(IDPRODUIT) REFERENCES PRODUITS(ID)
);